name: Build iPhone 7 UEFI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      GCC5_AARCH64_PREFIX: /usr/bin/
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq gcc nasm
          pip3 install --upgrade pip
          pip3 install -r pip-requirements.txt

      - name: Remove NASM NuGet dep
        run: rm -f MU_BASECORE/BaseTools/Bin/nasm_ext_dep.yaml

      - name: Update & Build
        run: |
          stuart_update -c Platform/iPhone7Pkg/PlatformBuild.py TOOL_CHAIN_TAG=GCC5
          stuart_build -c Platform/iPhone7Pkg/PlatformBuild.py TOOL_CHAIN_TAG=GCC5 TARGET=DEBUG
          
      - uses: actions/upload-artifact@v4
        with:
          name: iPhone7-UEFI
          path: Build/iPhone7-AARCH64/DEBUG_GCC5/FV/
